export SPARQL_BACKEND=stardog
export SPARQL_SEEDS=5
export SPARQL_TIMEOUT_MINS=5
export SFACTOR=sf1
export SPLIT_TRIPLE_SIZE=500M
export SEED_PATH=
export RDF_DATA_DIR=

export VIRTUOSO_HOME=
export VIRTUOSO_AVAILABLE_MEMORY_GB=8
export VIRTUOSO_DB_SIZE_GB=10
export VIRTUOSO_LOADERS=4

export STARDOG_HOME=
export STARDOG_SERVER_JAVA_ARGS="-Xms8G -Xmx8G -XX:MaxDirectMemorySize=16G"

